import React from 'react';
import { AbsoluteFill, useCurrentFrame, interpolate, Easing } from 'remotion';
import { IDELayout } from '../components/IDELayout';
import { AgentMessage } from '../components/AgentMessage';
import { CodeLine } from '../components/CodeLine';
import { Callout } from '../components/Callout';
import { FlashOverlay } from '../components/FlashOverlay';
import { SceneLabel } from '../components/SceneLabel';

const FILE_TREE = [
  { name: 'my-project', type: 'folder' as const, indent: 0 },
  { name: 'src', type: 'folder' as const, indent: 1 },
  { name: 'auth', type: 'folder' as const, indent: 2 },
  { name: 'email.ts', type: 'file' as const, indent: 3, highlight: true },
  { name: 'package.json', type: 'file' as const, indent: 1 },
];

const CODE_LINES = [
  { code: '// email.ts — generated by agent', color: '#6a9955' },
  { code: '' },
  { code: 'export async function sendVerification(email: string) {', color: '#d4d4d4' },
  { code: "  const token = crypto.randomUUID()  // no expiry!", color: '#f85149' },
  { code: "  await sendEmail(email, token)       // no retry", color: '#f85149' },
  { code: "  return token                        // no rate limit", color: '#f85149' },
  { code: '}', color: '#d4d4d4' },
  { code: '' },
  { code: '// ⚠️  No tests written', color: '#ffa657' },
  { code: '// ⚠️  No error handling', color: '#ffa657' },
  { code: '// ⚠️  No expiry, no rate limit', color: '#ffa657' },
];

const AGENT_MESSAGES = [
  { role: 'user' as const, text: 'Add email verification to the auth system', startFrame: 15 },
  { role: 'agent' as const, text: "Sure! I'll add that right away.", startFrame: 50 },
  { role: 'agent' as const, text: '⌨️  Writing email.ts...', startFrame: 100 },
  { role: 'agent' as const, text: '✅ Done! I created sendVerification() function.\n\nShipping now...', startFrame: 280, highlight: true },
  { role: 'system' as const, text: '$ git add . && git commit -m "add email"\n$ gh pr create', startFrame: 340 },
  { role: 'error' as const, text: '🔴 PR REVIEW: Changes Requested\n\n"No tests?"\n"Missing rate limiting"\n"No expiry on token?"\n"What if email fails?"', startFrame: 490, highlight: true },
];

export const WithoutHarness: React.FC = () => {
  const frame = useCurrentFrame();

  const sceneIn = interpolate(frame, [0, 20], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });
  const sceneOut = interpolate(frame, [720, 750], [1, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' });

  // Shake effect when PR is rejected
  const shakeX = frame >= 490 && frame <= 530
    ? Math.sin((frame - 490) * 1.5) * interpolate(frame, [490, 530], [8, 0], {
        extrapolateLeft: 'clamp', extrapolateRight: 'clamp',
      })
    : 0;

  const editorContent = (
    <div>
      {CODE_LINES.map((line, i) => (
        <CodeLine
          key={i}
          lineNum={i + 1}
          code={line.code}
          color={line.color}
          frame={frame}
          startFrame={130 + i * 15}
          isNew={i >= 2 && i <= 6}
        />
      ))}
    </div>
  );

  const agentPanel = (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 0, overflow: 'hidden', height: '100%' }}>
      {AGENT_MESSAGES.map((msg, i) => (
        <AgentMessage
          key={i}
          role={msg.role}
          text={msg.text}
          frame={frame}
          startFrame={msg.startFrame}
          highlight={msg.highlight}
        />
      ))}
    </div>
  );

  const bottomPanel = (
    <div style={{ fontFamily: "'Fira Code', monospace", fontSize: 13 }}>
      <div style={{ color: '#56d364', opacity: interpolate(frame, [340, 360], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }) }}>
        $ git add . && git commit -m "add email verification"
      </div>
      <div style={{ color: '#56d364', opacity: interpolate(frame, [370, 385], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }) }}>
        $ gh pr create --title "Add email verification"
      </div>
      <div style={{ color: '#ffa657', opacity: interpolate(frame, [400, 415], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }) }}>
        ✓ PR #42 opened — https://github.com/org/repo/pull/42
      </div>
      <div style={{ color: '#f85149', opacity: interpolate(frame, [500, 515], [0, 1], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }), fontWeight: 700 }}>
        ✗ CHANGES REQUESTED — 4 review comments
      </div>
    </div>
  );

  return (
    <AbsoluteFill style={{ opacity: sceneIn * sceneOut, transform: `translateX(${shakeX}px)` }}>
      <SceneLabel label="WITHOUT HARNESS" color="#f85149" />

      <div style={{ position: 'absolute', inset: 0, top: 60 }}>
        <IDELayout
          fileTree={FILE_TREE}
          editorContent={editorContent}
          agentPanel={agentPanel}
          bottomPanel={bottomPanel}
          activeFile="src/auth/email.ts"
        />
      </div>

      {/* Callouts */}
      <Callout
        text="Coding without a plan!"
        type="warning"
        frame={frame}
        startFrame={90}
        endFrame={300}
        top="35%"
        left="38%"
      />

      <Callout
        text="PR Rejected! 3 review cycles ahead"
        type="danger"
        frame={frame}
        startFrame={500}
        top="30%"
        left="38%"
      />

      {/* Flash on PR rejection */}
      <FlashOverlay frame={frame} startFrame={490} color="#f85149" duration={25} />
    </AbsoluteFill>
  );
};
